DROP TABLE IF EXISTS cy_sys_user_role;

DROP TABLE IF EXISTS cy_sys_role;

DROP TABLE IF EXISTS cy_sys_user;

DROP TABLE IF EXISTS cy_sys_team;

DROP TABLE IF EXISTS cy_sys_resource;

DROP TABLE IF EXISTS cy_sys_user_online;

DROP TABLE IF EXISTS cy_sys_permission;

DROP TABLE IF EXISTS cy_sys_role_resource_permission;

DROP TABLE IF EXISTS cy_sys_authorize;


CREATE TABLE cy_sys_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL UNIQUE,
	value VARCHAR(255) NOT NULL UNIQUE,
	permissions TEXT,
	description TEXT,
PRIMARY KEY (id)
);

CREATE TABLE cy_sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(64),
  password VARCHAR(255),
  salt VARCHAR(64),
  email VARCHAR(128),
  tel VARCHAR (20) UNIQUE,
  status VARCHAR(32),
  team_ID BIGINT,
  create_DATE DATETIME,
  deleted INT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE cy_sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE cy_sys_team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL UNIQUE,
	master_id BIGINT,
  PRIMARY KEY (id)
);


CREATE TABLE cy_sys_resource
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  icon VARCHAR(255),
  _identity VARCHAR(255),
  parent_id BIGINT,
  parent_ids VARCHAR(255),
  url VARCHAR(255),
  weight INT,
  is_show BIT,
  resource_type INT,
  PRIMARY KEY (id)
);

CREATE TABLE cy_sys_user_online
(
  id VARCHAR(255),
  host VARCHAR(255),
  last_access_time DATETIME,
  online_session LONGTEXT,
  start_timestamp DATETIME,
  status VARCHAR(255),
  system_host VARCHAR(255),
  timeout BIGINT,
  user_agent VARCHAR(255),
  user_id BIGINT,
  username VARCHAR(255),
  PRIMARY KEY (id)
);


CREATE TABLE cy_sys_permission
(
    id BIGINT(20) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    value VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE cy_sys_role_resource_permission(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role_id BIGINT,
  resource_id BIGINT,
  permission_ids VARCHAR(500),,
  PRIMARY KEY (id)
);
ALTER TABLE cy_sys_role_resource_permission  ADD  CONSTRAINT unique_sys_role_resource_permission UNIQUE(role_id, resource_id);

CREATE TABLE cy_sys_authorize
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    auth_type VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

create table cy_maintain_task_definition
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(300) null,
    cron varchar(300) null,
    bean_class varchar(300) null,
    bean_name varchar(300) null,
    method_Name varchar(300) null,
    start tinyint(1) null,
    description varchar(4000) null,
    PRIMARY KEY (id)
);

CREATE TABLE DS_SOURCE_MANAGE
(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  DS_NAME VARCHAR(200) NOT NULL,
  DS_TYPE VARCHAR(200) NOT NULL,
  DB_NAME VARCHAR(200) NOT NULL,
  DB_TYPE VARCHAR(200) NOT NULL,
  DB_HOST VARCHAR(200) NOT NULL,
  DB_PORT VARCHAR(200) NOT NULL,
  DB_USERNAME VARCHAR(200) NOT NULL,
  DB_PASSWORD VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
);
